import { describe, expect, it } from "vitest";
import { TypeScriptBackend } from "./typescript.js";
import {
  alt,
  float,
  generate,
  generateCtx,
  int,
  lit,
  namedAlt,
  opt,
  path,
  rep,
  repJoin,
  seq,
  seqJoin,
  str,
} from "./test-helpers.js";

describe("TypeScript generation - structure", () => {
  it("emits auto-generated header and styxdefs imports", () => {
    const code = generate(seq(lit("tool")));
    expect(code).toContain("// This file was auto generated by Styx.");
    expect(code).toContain(
      'import type { Runner, Execution, Metadata, InputPathType } from "styxdefs"',
    );
    expect(code).toContain('import { getGlobalRunner } from "styxdefs"');
  });

  it("emits metadata constant with Metadata type", () => {
    const code = generate(seq(lit("bet")), {
      app: { id: "bet", doc: { title: "bet", description: "Brain extraction" } },
      package: { name: "fsl" },
    });
    expect(code).toContain("const BET_METADATA: Metadata");
    expect(code).toContain('id: "bet"');
    expect(code).toContain('name: "bet"');
    expect(code).toContain('package: "fsl"');
  });

  it("emits wrapper function using styxdefs runner protocol", () => {
    const code = generate(seq(lit("tool"), str("input")), {
      app: { id: "my-tool" },
    });
    expect(code).toContain("export function myTool(");
    expect(code).toContain("runner = runner ?? getGlobalRunner()");
    expect(code).toContain("runner.startExecution(MY_TOOL_METADATA)");
    expect(code).toContain("execution.params(params)");
    expect(code).toContain("execution.run(cargs)");
  });
});

describe("TypeScript generation - type declarations", () => {
  it("generates interface for struct with string field", () => {
    const code = generate(seq(lit("tool"), str("name")));
    expect(code).toContain("export interface");
    expect(code).toContain("name: string");
  });

  it("generates interface for struct with multiple scalar types", () => {
    const code = generate(seq(str("input"), int("count"), float("ratio")));
    expect(code).toContain("input: string");
    expect(code).toContain("count: number");
    expect(code).toContain("ratio: number");
  });

  it("maps path to InputPathType", () => {
    const code = generate(seq(path("infile")));
    expect(code).toContain("infile: InputPathType");
  });

  it("maps optional to nullable optional field", () => {
    const code = generate(seq(opt(str("name"))));
    expect(code).toMatch(/name\?: string \| null/);
  });

  it("maps repeat to array type", () => {
    const code = generate(seq(rep(str("item"), "items")));
    expect(code).toContain("string[]");
  });

  it("maps literal union (alternative of literals) to string union", () => {
    const code = generate(seq(alt(lit("a"), lit("b"), lit("c"))));
    expect(code).toMatch(/"a"\s*\|\s*"b"\s*\|\s*"c"/);
  });

  it("emits @type discriminator on root params interface", () => {
    const code = generate(seq(str("input")), {
      app: { id: "bet" },
      package: { name: "fsl" },
    });
    expect(code).toContain('"@type"?: "fsl/bet"');
  });

  it("marks fields with defaultValue as optional", () => {
    const code = generate(seq(opt(seq(lit("-v")), { name: "verbose", defaultValue: false })));
    expect(code).toMatch(/verbose\?: boolean/);
  });
});

describe("TypeScript generation - JSDoc", () => {
  it("emits JSDoc for fields with descriptions", () => {
    const code = generate(seq(str("input", "An important parameter")));
    expect(code).toContain("/** An important parameter */");
  });

  it("emits function-level JSDoc from app metadata", () => {
    const code = generate(seq(lit("tool")), {
      app: {
        id: "bet",
        doc: { title: "bet", description: "Brain extraction tool" },
      },
    });
    expect(code).toContain("Brain extraction tool");
    expect(code).toContain("@param params");
    expect(code).toContain("@param runner");
  });

  it("includes author and URL in function JSDoc", () => {
    const code = generate(seq(lit("tool")), {
      app: {
        id: "tool",
        doc: {
          title: "tool",
          authors: ["Alice", "Bob"],
          urls: ["https://example.com"],
        },
      },
    });
    expect(code).toContain("Author: Alice, Bob");
    expect(code).toContain("URL: https://example.com");
  });

  it("emits JSDoc for multiple root fields", () => {
    const code = generate(seq(str("input", "The input file"), str("output", "The output file")));
    expect(code).toContain("/** The input file */");
    expect(code).toContain("/** The output file */");
  });

  it("emits JSDoc for optional scalar field (doc on inner terminal)", () => {
    const code = generate(seq(lit("cmd"), opt(seq(lit("--out"), str("output", "Output path")))));
    expect(code).toContain("/** Output path */");
    expect(code).toContain("output?:");
  });

  it("emits JSDoc for fields inside repeat struct", () => {
    const code = generate(
      seq(
        lit("cmd"),
        rep(
          seq(
            str("name", "Entry name"),
            int({ name: "value", doc: { description: "Entry value" } }),
          ),
          "entries",
        ),
      ),
    );
    expect(code).toContain("/** Entry name */");
    expect(code).toContain("/** Entry value */");
    // Root entries field should NOT steal nested doc
    const rootInterface = code.match(/export interface \w+ \{[\s\S]*?\n\}/)?.[0] ?? "";
    expect(rootInterface).not.toContain("Entry name");
  });

  it("emits JSDoc for fields inside optional struct", () => {
    const code = generate(
      seq(
        lit("cmd"),
        opt(
          seq(
            lit("--range"),
            int({ name: "min", doc: { description: "Minimum value" } }),
            int({ name: "max", doc: { description: "Maximum value" } }),
          ),
          { name: "range" },
        ),
      ),
    );
    expect(code).toContain("/** Minimum value */");
    expect(code).toContain("/** Maximum value */");
    // Root range field should NOT steal nested doc
    const rootInterface = code.match(/export interface \w+ \{[\s\S]*?\n\}/)?.[0] ?? "";
    expect(rootInterface).not.toContain("Minimum value");
  });

  it("emits JSDoc from opt node meta (hoisted doc)", () => {
    const code = generate(
      seq(
        lit("cmd"),
        opt(seq(lit("--out"), str("output")), {
          name: "output",
          doc: { description: "Output file path" },
        }),
      ),
    );
    expect(code).toContain("/** Output file path */");
  });

  it("emits JSDoc for optional repeat (collapsed access)", () => {
    const code = generate(
      seq(
        lit("cmd"),
        opt(seq(lit("--items"), rep(int({ name: "v", doc: { description: "A value" } }), "vals")), {
          name: "items",
        }),
      ),
    );
    expect(code).toContain("/** A value */");
  });

  it("emits multi-line JSDoc for long descriptions", () => {
    const code = generate(
      seq(str("input", "First line of the description.\nSecond line with more detail.")),
    );
    expect(code).toContain("/**");
    expect(code).toContain(" * First line of the description.");
    expect(code).toContain(" * Second line with more detail.");
    expect(code).toContain(" */");
  });

  it("emits JSDoc through double-nested collapsed sequence", () => {
    // Simulates: opt(seq(--flag, seq(subcommand, str)))
    // After solver collapse, the binding is 2 levels deep in sequences
    const code = generate(
      seq(
        lit("cmd"),
        opt(
          seq(
            lit("--transform"),
            seq(lit("rigid"), str("config", "Transform configuration file")),
          ),
          { name: "transform" },
        ),
      ),
    );
    expect(code).toContain("/** Transform configuration file */");
  });

  it("does not leak doc from parent struct to nested struct field with same binding name", () => {
    // Parent and nested struct both have a field; doc should not leak between them
    const code = generate(
      seq(
        str("name", "Top-level name"),
        rep(
          seq(
            str("name", "Nested name"),
            int({ name: "value", doc: { description: "Nested value" } }),
          ),
          "items",
        ),
      ),
    );
    // The nested struct's "name" field should have "Nested name"
    const nestedInterface = code.match(
      /export interface \w+ \{[\s\S]*?Nested name[\s\S]*?\n\}/,
    )?.[0];
    expect(nestedInterface).toBeTruthy();
    expect(nestedInterface).toContain("/** Nested name */");
    expect(nestedInterface).toContain("/** Nested value */");
  });
});

describe("TypeScript generation - cargs building", () => {
  it("pushes literal strings", () => {
    const code = generate(seq(lit("tool"), str("input")));
    expect(code).toContain('cargs.push("tool")');
  });

  it("pushes string params directly (no String())", () => {
    const code = generate(seq(str("name")));
    expect(code).toContain("cargs.push(params.name)");
  });

  it("wraps int params with String()", () => {
    const code = generate(seq(int("count")));
    expect(code).toContain("cargs.push(String(params.count))");
  });

  it("uses execution.inputFile for path params", () => {
    const code = generate(seq(path("infile")));
    expect(code).toContain("cargs.push(execution.inputFile(params.infile))");
  });

  it("emits null check for optional params", () => {
    const code = generate(seq(opt(str("name"))));
    expect(code).toContain("if (params.name != null)");
  });

  it("emits truthy check for bool flags", () => {
    const code = generate(seq(opt(seq(lit("-v")))));
    expect(code).toMatch(/if \(params\.\w+\)/);
  });

  it("emits for-of loop for list params with correct loop variable", () => {
    const code = generate(seq(rep(int("val"), "vals")));
    const match = code.match(/for \(const (\w+) of params\.vals\)/);
    expect(match).toBeTruthy();
    const itemVar = match![1];
    expect(code).toContain(`String(${itemVar})`);
    expect(code).not.toContain("String(params.vals)");
  });

  it("emits for loop for count params", () => {
    const code = generate(seq(rep(seq(lit("-v")), "verbosity")));
    expect(code).toMatch(/for \(let \w+ = 0;/);
  });

  it("handles nested optional with flag and value", () => {
    const code = generate(seq(opt(seq(lit("-f"), float("threshold")))));
    expect(code).toContain("if (params.threshold != null)");
    expect(code).toContain('cargs.push("-f")');
    expect(code).toContain("cargs.push(String(params.threshold))");
  });

  it("handles literal union alternative as String() push", () => {
    const code = generate(seq(alt(lit("fast"), lit("slow"))));
    expect(code).toContain('"fast" | "slow"');
    expect(code).toContain("cargs.push(String(params.");
  });
});

describe("TypeScript generation - complex IR", () => {
  it("handles sequence with mixed required and optional fields", () => {
    const code = generate(
      seq(
        lit("tool"),
        str("input"),
        opt(seq(lit("--threshold"), float("threshold"))),
        opt(seq(lit("-v")), { name: "verbose", defaultValue: false }),
      ),
    );
    expect(code).toContain("input: string");
    expect(code).toMatch(/threshold\?: number \| null/);
    expect(code).toMatch(/verbose\?: boolean/);
    expect(code).toContain('cargs.push("tool")');
    expect(code).toContain("if (params.verbose)");
  });

  it("handles repeat inside optional", () => {
    const code = generate(seq(opt(seq(lit("-c"), rep(float("coord"), "coords")))));
    expect(code).toMatch(/coords\?:/);
    expect(code).toContain("if (params.coords != null)");
    const match = code.match(/for \(const (\w+) of params\.coords\)/);
    expect(match).toBeTruthy();
  });

  it("handles alternative with non-literal variants (discriminated union)", () => {
    const expr = seq(alt(seq(lit("--file"), path("file")), seq(lit("--url"), str("url"))));
    const code = generate(expr);
    // Variant interfaces include @type discriminator
    expect(code).toContain('"@type": "variant_0"');
    expect(code).toContain('"@type": "variant_1"');
    // Switch dispatches on @type
    expect(code).toContain("switch");
    expect(code).toContain('case "variant_0"');
    expect(code).toContain('case "variant_1"');
  });

  it("handles deeply nested: seq > opt > seq > rep > int", () => {
    const code = generate(seq(lit("cmd"), opt(seq(lit("--dims"), rep(int("dim"), "dims")))));
    expect(code).toContain("number[]");
    expect(code).toContain('cargs.push("--dims")');
  });
});

describe("TypeScript generation - discriminated unions", () => {
  it("emits @type literal on each variant interface", () => {
    const code = generate(
      seq(namedAlt("source", seq(lit("--file"), path("file")), seq(lit("--url"), str("url")))),
    );
    // Each variant interface gets its @type discriminator
    expect(code).toContain('"@type": "variant_0"');
    expect(code).toContain("file: InputPathType");
    expect(code).toContain('"@type": "variant_1"');
    expect(code).toContain("url: string");
  });

  it("emits union type alias referencing variant interfaces", () => {
    const code = generate(
      seq(namedAlt("source", seq(lit("--file"), path("file")), seq(lit("--url"), str("url")))),
    );
    expect(code).toMatch(/export type \w+ = \w+ \| \w+/);
  });

  it("emits switch without type cast", () => {
    const code = generate(
      seq(namedAlt("source", seq(lit("--file"), path("file")), seq(lit("--url"), str("url")))),
    );
    // Should NOT have a cast - @type is now in the interface
    expect(code).not.toContain("as {");
    expect(code).toContain('switch (params.source["@type"])');
  });

  it("uses named variants when alt children have meta names", () => {
    const expr = seq({
      kind: "alternative" as const,
      attrs: {
        alts: [
          { ...seq(lit("--file"), path("file")), meta: { name: "by_file" } },
          { ...seq(lit("--url"), str("url")), meta: { name: "by_url" } },
        ],
      },
      meta: { name: "source" },
    });
    const code = generate(expr);
    expect(code).toContain('"@type": "by_file"');
    expect(code).toContain('"@type": "by_url"');
    expect(code).toContain('case "by_file"');
    expect(code).toContain('case "by_url"');
  });

  it("does not emit @type on literal union variant types", () => {
    const code = generate(seq(namedAlt("mode", lit("fast"), lit("slow"))));
    // Literal unions should NOT have @type - they're just string unions
    expect(code).not.toContain('"@type": "fast"');
    expect(code).not.toContain('"@type": "slow"');
    expect(code).toContain('"fast" | "slow"');
  });

  it("emits variant fields alongside @type discriminator", () => {
    const code = generate(
      seq(
        namedAlt(
          "input",
          seq(lit("--single"), path("file")),
          seq(lit("--batch"), rep(path("f"), "files")),
        ),
      ),
    );
    // First variant: @type + file field
    expect(code).toContain('"@type": "variant_0"');
    expect(code).toContain("file: InputPathType");
    // Second variant: @type + files array field
    expect(code).toContain('"@type": "variant_1"');
    expect(code).toContain("InputPathType[]");
  });

  it("emits correct cargs for each variant branch", () => {
    const code = generate(
      seq(
        lit("cmd"),
        namedAlt("source", seq(lit("--file"), path("file")), seq(lit("--url"), str("url"))),
      ),
      { app: { id: "t" } },
    );
    expect(code).toContain('cargs.push("--file")');
    expect(code).toContain("execution.inputFile(params.source.file)");
    expect(code).toContain('cargs.push("--url")');
    expect(code).toContain("params.source.url");
  });
});

describe("TypeScriptBackend", () => {
  it("emits a file map keyed by app id", () => {
    const ctx = generateCtx(seq(lit("bet"), str("input")), {
      app: { id: "bet", doc: { title: "bet" } },
    });
    const backend = new TypeScriptBackend();
    const result = backend.emit(ctx);

    expect(result.errors).toHaveLength(0);
    expect(result.files.has("bet.ts")).toBe(true);
    expect(result.files.get("bet.ts")).toContain("export function bet(");
  });

  it("uses output.ts when no app id", () => {
    const ctx = generateCtx(seq(str("input")));
    const backend = new TypeScriptBackend();
    const result = backend.emit(ctx);

    expect(result.files.has("output.ts")).toBe(true);
  });
});

describe("TypeScript generation - join", () => {
  it("joins sequence parts into single arg with empty separator", () => {
    const code = generate(seq(opt(seqJoin("", lit("-f"), str("file")))));
    expect(code).toContain('.join("")');
    expect(code).not.toMatch(/cargs\.push\("-f"\).*cargs\.push\(params\.file\)/s);
  });

  it("joins sequence parts with comma separator", () => {
    const code = generate(seq(opt(seqJoin(",", str("x"), str("y")))));
    expect(code).toContain('.join(",")');
  });

  it("joins repeat items into single arg with comma separator", () => {
    const code = generate(seq(repJoin(",", int("val"), "vals")));
    expect(code).toContain(".map(");
    expect(code).toContain('.join(",")');
    expect(code).not.toContain("for (const");
  });

  it("joins repeat items with space separator", () => {
    const code = generate(seq(repJoin(" ", str("item"), "items")));
    expect(code).toContain('.join(" ")');
    expect(code).not.toContain("for (const");
  });

  it("uses for-of loop when repeat has no join", () => {
    const code = generate(seq(rep(int("val"), "vals")));
    expect(code).toContain("for (const");
    expect(code).not.toContain(".join(");
  });

  it("handles repeat of joined sequence (flag+value concatenated per item)", () => {
    const code = generate(seq(repJoin(",", seqJoin("", lit("-d"), str("dir")), "dirs")));
    expect(code).toContain(".map(");
    expect(code).toContain('.join(",")');
    expect(code).toContain('.join("")');
  });

  it("handles optional wrapping a joined sequence", () => {
    const code = generate(seq(opt(seqJoin("=", lit("--output"), str("path")))));
    expect(code).toContain("if (params.path != null)");
    expect(code).toContain('.join("=")');
    const pushCount = (code.match(/cargs\.push/g) || []).length;
    expect(pushCount).toBe(1);
  });

  it("handles repeat with join inside optional", () => {
    const code = generate(seq(opt(seq(lit("-c"), repJoin(",", float("coord"), "coords")))));
    expect(code).toContain("if (params.coords != null)");
    expect(code).toContain('.join(",")');
    expect(code).toContain(".map(");
    expect(code).toContain('cargs.push("-c")');
  });

  it("handles joined sequence with literal union alternative", () => {
    const code = generate(seq(seqJoin("=", lit("--mode"), alt(lit("fast"), lit("slow")))));
    expect(code).toContain('.join("=")');
    expect(code).toContain('"--mode"');
  });

  it("handles nested: opt > seq > rep(join) > int", () => {
    const code = generate(seq(opt(seq(lit("--dims"), repJoin("x", int("dim"), "dims")))));
    expect(code).toContain("if (params.dims != null)");
    expect(code).toContain('cargs.push("--dims")');
    expect(code).toContain('.join("x")');
    expect(code).toContain(".map(");
    expect(code).not.toContain("for (const");
  });

  it("handles joined sequence with path (uses execution.inputFile)", () => {
    const code = generate(seq(seqJoin("=", lit("--input"), path("file"))));
    expect(code).toContain("execution.inputFile");
    expect(code).toContain('.join("=")');
  });

  it("handles repeat(join) of paths", () => {
    const code = generate(seq(repJoin(":", path("p"), "paths")));
    expect(code).toContain("execution.inputFile");
    expect(code).toContain('.join(":")');
    expect(code).toContain(".map(");
  });
});
