import type { CodegenContext } from "../../manifest/index.js";
import type { Backend, EmitResult } from "../backend.js";
import { CodeBuilder } from "../code-builder.js";
import { Scope } from "../scope.js";
import { camelCase, pascalCase, screamingSnakeCase } from "../string-case.js";
import {
  emitBuildCargs,
  emitImports,
  emitMetadata,
  emitTypeDeclarations,
  emitWrapperFunction,
} from "./emit.js";
import { mapType } from "./typemap.js";
import { collectNamedTypes, resolveTypeName, structKey, unionKey } from "./types.js";

const TS_RESERVED = [
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "enum",
  "export",
  "extends",
  "false",
  "finally",
  "for",
  "function",
  "if",
  "import",
  "in",
  "instanceof",
  "new",
  "null",
  "return",
  "super",
  "switch",
  "this",
  "throw",
  "true",
  "try",
  "typeof",
  "undefined",
  "var",
  "void",
  "while",
  "with",
  "yield",
  "let",
  "static",
  "implements",
  "interface",
  "package",
  "private",
  "protected",
  "public",
  "type",
];

export function generateTypeScript(ctx: CodegenContext): string {
  const cb = new CodeBuilder("  ");
  const scope = new Scope(TS_RESERVED);

  const appId = ctx.app?.id;
  const pkg = ctx.package?.name ?? "unknown";

  // Reserve names
  scope.add("metadata");

  const rootBinding = ctx.resolve(ctx.expr);
  const rootType = rootBinding?.type ?? { kind: "struct" as const, fields: {} };

  const rootName = appId ? pascalCase(appId) : "Params";
  const { namedTypes, typeDecls } = collectNamedTypes(rootType, rootName, scope);

  // Auto-generated header
  cb.comment("This file was auto generated by Styx.");
  cb.comment("Do not edit this file directly.");
  cb.blank();

  // Imports from styxdefs
  emitImports(cb);
  cb.blank();

  // Metadata constant
  const metaConst = screamingSnakeCase(appId ?? "TOOL") + "_METADATA";
  emitMetadata(ctx, metaConst, cb);
  cb.blank();

  // Type declarations (interfaces, unions)
  emitTypeDeclarations(typeDecls, namedTypes, ctx, appId, pkg, cb);

  // Determine the params type name
  const paramsType =
    (rootType.kind === "struct" ? namedTypes.get(structKey(rootType)) : undefined) ??
    (rootType.kind === "union" ? namedTypes.get(unionKey(rootType)) : undefined) ??
    mapType(rootType, resolveTypeName(namedTypes));

  // Build cargs function
  emitBuildCargs(ctx, rootType, paramsType, cb);
  cb.blank();

  // Wrapper function
  const funcName = scope.add(camelCase(appId ?? "run"));
  emitWrapperFunction(ctx, paramsType, funcName, metaConst, cb);
  cb.blank();

  return cb.toString();
}

export class TypeScriptBackend implements Backend {
  readonly name = "typescript";
  readonly target = "typescript";

  emit(ctx: CodegenContext): EmitResult {
    const code = generateTypeScript(ctx);
    const filename = ctx.app?.id ? `${ctx.app.id}.ts` : "output.ts";
    return {
      files: new Map([[filename, code]]),
      errors: [],
      warnings: [],
    };
  }
}
